worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: false

server-port: 8082
db-url: 'postgresql://app_auth:bbc0cf7ab506a12f8aa3add9db6ba1b@localhost:15433/app_auth'

oidc-client-id: web
oidc-client-secret: 
oidc-provider-url: http://localhost:8081/realms/svetit
