worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: true

server-port: 8082
db-url: 'postgresql://auth:bbc0cf7ab506a12f8aa3add9db6ba1b@localhost:15433/auth'

oidc-client-id: web
oidc-client-secret: ALvl2s4drrwetGbhSeiVJnTKpAPP5hJs
oidc-provider-url: http://localhost:8081/realms/svetit

token-cookie-max-age: 15
