components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        database:
          dbconnection: $db-url
          blocking_task_processor: fs-task-processor
          dns_resolver: async
          sync-start: true

        tokenizer:
          internalTlsKeyPath: $internal-tls-key-path

        oidc:
          client-id: $oidc-client-id
          client-secret: $oidc-client-secret
          provider-url: $oidc-provider-url
          provider-url-admin: $oidc-provider-url-admin

        repository: {}
        main-service:
          web-login-path: /login/complete
          web-logout-path: /logout/complete
          web-error-page-path: /logout
          items-limit-for-list: $items-limit-for-list
          json-schemas-path: $json-schemas-path

        tests-control:
            load-enabled: $is_testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-token-introspect:
          path: /auth/token/introspect
          method: GET
          task_processor: main-task-processor

        handler-token-refresh:
          path: /auth/token/refresh
          method: POST
          task_processor: main-task-processor

        handler-login:
          path: /auth/login
          method: GET
          task_processor: main-task-processor

        handler-login-callback:
          path: /auth/login/callback
          method: GET
          task_processor: main-task-processor

        handler-logout:
          path: /auth/logout
          method: GET
          task_processor: main-task-processor

        handler-logout-callback:
          path: /auth/logout/callback
          method: GET
          task_processor: main-task-processor

        handler-user-info:
          path: /user/info
          method: GET
          task_processor: main-task-processor

        handler-user-byid:
          path: /user/{id}
          method: GET
          task_processor: main-task-processor

        handler-user-list:
          path: /user/list
          method: GET
          task_processor: main-task-processor
