/* pgmigrate-encoding: utf-8 */
CREATE SCHEMA IF NOT EXISTS auth;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE auth.session (
	id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	token TEXT NOT NULL,
	created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
	expired_at BIGINT NOT NULL,
	user_id VARCHAR(36) NOT NULL,
	device TEXT NOT NULL,
	access_token TEXT NOT NULL,
	refresh_token TEXT NOT NULL,
	id_token TEXT NOT NULL,
	active BOOLEAN NOT NULL
);

CREATE TABLE auth.state (
	id SERIAL PRIMARY KEY,
	state TEXT NOT NULL,
	redirect_url TEXT NOT NULL,
	created_at BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);
