openapi: "3.0.0"
info:
  version: 1.0.0
  title: Svetit MS Project
  license:
    name: Apache-2.0
servers:
  - url: https://svetit-io/api
paths:
  /project/project/list:
    get:
      summary: List all projects
      operationId: handler-project-list-get
      tags:
        - main
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 1000)
          required: true
          schema:
            type: integer
            maximum: 1000
            format: int32
        - name: start
          in: query
          description: Offset position
          required: true
          schema:
            type: integer
            maximum: 999
            format: int32
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A paged array of projects
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Projects"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /project/project:
    get:
      summary: Get one project
      operationId: handler-project-get
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Project identifier
          required: false
          schema:
            type: string
            format: uuid
        - name: key
          in: query
          description: Project key
          required: false
          schema:
            type: string
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A project object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a project
      operationId: handler-project-post
      tags:
        - main
      parameters:
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Update a project
      operationId: handler-project-patch
      tags:
        - main
      parameters:
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              Project:
                type: object
                required:
                  - id
                  - spaceId
                  - key
                  - name
                  - sync
                properties:
                  id:
                    type: string
                    format: uuid
                  spaceId:
                    type: string
                    format: uuid
                  key:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  changedAt:
                    type: integer
                    format: int64
                  sync:
                    type: string
                    enum:
                      - projectToNode
                      - nodeToProject
        required: true
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete project
      operationId: handler-project-delete
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Project identifier
          required: true
          schema:
            type: string
            format: uuid
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A project object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Project"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /project/project/section:
    get:
      summary: Get one section
      operationId: handler-section-get
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Section identifier
          required: false
          schema:
            format: int64
            type: integer
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A section object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Section"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a section
      operationId: handler-section-post
      tags:
        - main
      parameters:
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Section'
        required: true
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Update a section
      operationId: handler-section-patch
      tags:
        - main
      parameters:
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              Section:
                $ref: '#/components/schemas/Section'
        required: true
      responses:
        '204':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete section
      operationId: handler-section-delete
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Section identifier
          required: true
          schema:
            type: integer
            format: int64
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /project/project/param-type:
    get:
      summary: Get one param-type
      operationId: handler-param-type-get
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Param type identifier
          required: false
          schema:
            format: int64
            type: integer
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A param type object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ParamType"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a param type
      operationId: handler-param-type-post
      tags:
        - main
      parameters:
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParamType'
        required: true
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    patch:
      summary: Update a param type
      operationId: handler-param-type-patch
      tags:
        - main
      parameters:
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              Section:
                $ref: '#/components/schemas/ParamType'
        required: true
      responses:
        '204':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete param type
      operationId: handler-param-type-delete
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Param identifier
          required: true
          schema:
            type: integer
            format: int64
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /space/invitation:
    put:
      summary: Change role in invitation
      operationId: handler-space-invitation-put
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Invitation identifier
          required: true
          schema:
            format: int64
            type: integer
        - name: test
          in: query
          description: Invitation test
          required: false
          schema:
            format: date
            type: string
        - name: X-User
          in: header
          description: Authorized user
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Role"
        required: true
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: Delete invitation
      operationId: handler-space-invitation-delete
      tags:
        - main
      parameters:
        - name: id
          in: query
          description: Invitation identifier
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Project:
      type: object
      required:
        - spaceId
        - key
        - name
        - sync
      properties:
        id:
          type: string
          format: uuid
        spaceId:
          type: string
          format: uuid
        key:
          type: string
        name:
          type: string
        description:
          type: string
        changedAt:
          type: integer
          format: int64
        sync:
          type: string
          enum:
            - projectToNode
            - nodeToProject
    Projects:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Project"
    Section:
      type: object
      required:
        - projectId
        - name
      properties:
        id:
          type: integer
          format: int64
        projectId:
          type: string
          format: uuid
        name:
          type: string
    ParamType:
      type: object
      required:
        - parentId
        - key
        - name
        - description
        - valueType
      properties:
        id:
          type: integer
          format: int64
        parentId:
          type: string
          nullable: true
          format: uuid
        key:
          type: string
        name:
          type: string
        description:
          type: string
        valueType:
          type: string
          enum:
            - int
            - bool
            - float
            - string
            - bytes
            - time
            - range
            - combo
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Role:
      type: object
      properties:
        role:
          type: string
          maxLength: 5
          minLength: 4
      required:
        - role