openapi: 3.0.0
info:
  version: 1.0.0
  title: Svetit MS Project
  license:
    name: Apache-2.0
servers:
  - url: https://svetit-io/api
tags:
  - name: auth
    description: ms Auth
  - name: space
    description: ms Space
  - name: project
    description: ms Project
  - name: node
    description: ms Node
paths:
  /s/{spaceKey}/project:
    $ref: paths/project_project.yaml
  /s/{spaceKey}/project/list:
    $ref: paths/project_list.yaml
  /s/{spaceKey}/project/project-param:
    $ref: paths/project_project-param.yaml
  /s/{spaceKey}/project/project-param/list:
    $ref: paths/project_project-param_list.yaml
  /s/{spaceKey}/project/section:
    $ref: paths/project_section.yaml
  /s/{spaceKey}/project/section/list:
    $ref: paths/project_section_list.yaml
  /s/{spaceKey}/project/section-param:
    $ref: paths/project_section-param.yaml
  /s/{spaceKey}/project/section-param/list:
    $ref: paths/project_section-param_list.yaml
  /s/{spaceKey}/project/cc-mode-type:
    $ref: paths/project_cc-mode-type.yaml
  /s/{spaceKey}/project/cc-mode-type/list:
    $ref: paths/project_cc-mode-type_list.yaml
  /s/{spaceKey}/project/cc-status-category:
    $ref: paths/project_cc-status-category.yaml
  /s/{spaceKey}/project/cc-status-category/list:
    $ref: paths/project_cc-status-category_list.yaml
  /s/{spaceKey}/project/cc-status-type:
    $ref: paths/project_cc-status-type.yaml
  /s/{spaceKey}/project/cc-status-type/list:
    $ref: paths/project_cc-status-type_list.yaml
  /s/{spaceKey}/project/cc-type:
    $ref: paths/project_cc-type.yaml
  /s/{spaceKey}/project/cc-type/list:
    $ref: paths/project_cc-type_list.yaml
  /s/{spaceKey}/project/code:
    $ref: paths/project_code.yaml
  /s/{spaceKey}/project/code/list:
    $ref: paths/project_code_list.yaml
  /s/{spaceKey}/project/control-circuit:
    $ref: paths/project_control-circuit.yaml
  /s/{spaceKey}/project/control-circuit/list:
    $ref: paths/project_control-circuit_list.yaml
  /s/{spaceKey}/project/device-item:
    $ref: paths/project_device-item.yaml
  /s/{spaceKey}/project/device-item/list:
    $ref: paths/project_device-item_list.yaml
  /s/{spaceKey}/project/device:
    $ref: paths/project_device.yaml
  /s/{spaceKey}/project/device/list:
    $ref: paths/project_device_list.yaml
  /s/{spaceKey}/project/di-type:
    $ref: paths/project_di-type.yaml
  /s/{spaceKey}/project/di-type/list:
    $ref: paths/project_di-type_list.yaml
  /s/{spaceKey}/project/measure:
    $ref: paths/project_measure.yaml
  /s/{spaceKey}/project/measure/list:
    $ref: paths/project_measure_list.yaml
  /s/{spaceKey}/project/plugin:
    $ref: paths/project_plugin.yaml
  /s/{spaceKey}/project/plugin/list:
    $ref: paths/project_plugin_list.yaml
  /s/{spaceKey}/project/save-timer:
    $ref: paths/project_save-timer.yaml
  /s/{spaceKey}/project/save-timer/list:
    $ref: paths/project_save-timer_list.yaml
  /s/{spaceKey}/project/translation:
    $ref: paths/project_translation.yaml
  /s/{spaceKey}/project/translation/list:
    $ref: paths/project_translation_list.yaml
  /s/{spaceKey}/project/value-view:
    $ref: paths/project_value-view.yaml
  /s/{spaceKey}/project/value-view/list:
    $ref: paths/project_value-view_list.yaml
  /s/{spaceKey}/project/param-type:
    $ref: paths/project_param-type.yaml
  /s/{spaceKey}/project/param-type/list:
    $ref: paths/project_param-type_list.yaml
  /s/{spaceKey}/project/cc-di:
    $ref: paths/project_cc-di.yaml
  /s/{spaceKey}/project/cc-di/list:
    $ref: paths/project_cc-di_list.yaml
  /s/{spaceKey}/project/cc-param:
    $ref: paths/project_cc-param.yaml
  /s/{spaceKey}/project/cc-param/list:
    $ref: paths/project_cc-param_list.yaml
  /s/{spaceKey}/project/cc-type-di-type:
    $ref: paths/project_cc-type-di-type.yaml
  /s/{spaceKey}/project/cc-type-di-type/list:
    $ref: paths/project_cc-type-di-type_list.yaml
  /s/{spaceKey}/project/cc-type-param:
    $ref: paths/project_cc-type-param.yaml
  /s/{spaceKey}/project/cc-type-param/list:
    $ref: paths/project_cc-type-param_list.yaml
  /s/{spaceKey}/project/device-plugin-param:
    $ref: paths/project_device-plugin-param.yaml
  /s/{spaceKey}/project/device-plugin-param/list:
    $ref: paths/project_device-plugin-param_list.yaml
  /s/{spaceKey}/project/di-plugin-param:
    $ref: paths/project_di-plugin-param.yaml
  /s/{spaceKey}/project/di-plugin-param/list:
    $ref: paths/project_di-plugin-param_list.yaml
  /auth/token/refresh:
    $ref: paths/auth_token_refresh.yaml
  /auth/login:
    $ref: paths/auth_login.yaml
  /auth/logout:
    $ref: paths/auth_logout.yaml
  /auth/login/callback:
    $ref: paths/auth_login_callback.yaml
  /auth/logout/callback:
    $ref: paths/auth_logout_callback.yaml
  /auth/token/introspect:
    $ref: paths/auth_token_introspect.yaml
  /user/info:
    $ref: paths/user_info.yaml
  /user/{id}:
    $ref: paths/user_{id}.yaml
  /user/list:
    $ref: paths/user_list.yaml
  /space/info:
    $ref: paths/space_info.yaml
  /space/invitation:
    $ref: paths/space_invitation.yaml
  /space/invitation/link:
    $ref: paths/space_invitation_link.yaml
  /space/list:
    $ref: paths/space_list.yaml
  /space/available/list:
    $ref: paths/space_available_list.yaml
  /space:
    $ref: paths/space_space.yaml
  /space/user:
    $ref: paths/space_user.yaml
  /space/user/list:
    $ref: paths/space_user_list.yaml
  /space/introspect:
    $ref: paths/space_introspect.yaml
  /s/{spaceKey}/space/group:
    $ref: paths/space_group.yaml
  /s/{spaceKey}/space/group/list:
    $ref: paths/space_group_list.yaml
  /s/{spaceKey}/space/role:
    $ref: paths/space_role.yaml
  /s/{spaceKey}/space/role/list:
    $ref: paths/space_role_list.yaml
  /s/{spaceKey}/node/node:
    $ref: paths/node_node.yaml
  /s/{spaceKey}/node/list:
    $ref: paths/node_list.yaml
  /node/project:
    $ref: paths/node_project.yaml
  /node/project/list:
    $ref: paths/node_project_list.yaml
  /node/group:
    $ref: paths/node_group.yaml
  /node/group/list:
    $ref: paths/node_group_list.yaml
  /group/user:
    $ref: paths/group_user.yaml
  /group/user/list:
    $ref: paths/group_user_list.yaml
