export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './node.service';
import { NodeService } from './node.service';
export * from './node.serviceInterface';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './project.serviceInterface';
export * from './space.service';
import { SpaceService } from './space.service';
export * from './space.serviceInterface';
export const APIS = [AuthService, NodeService, ProjectService, SpaceService];
