/**
 * Svetit MS Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CcDi } from '../model/models';
import { CcDis } from '../model/models';
import { CcModeType } from '../model/models';
import { CcModeTypes } from '../model/models';
import { CcParam } from '../model/models';
import { CcParams } from '../model/models';
import { CcStatusCategories } from '../model/models';
import { CcStatusCategory } from '../model/models';
import { CcStatusType } from '../model/models';
import { CcStatusTypes } from '../model/models';
import { CcType } from '../model/models';
import { CcTypeDiType } from '../model/models';
import { CcTypeDiTypes } from '../model/models';
import { CcTypeParam } from '../model/models';
import { CcTypeParams } from '../model/models';
import { CcTypes } from '../model/models';
import { Code } from '../model/models';
import { Codes } from '../model/models';
import { ControlCircuit } from '../model/models';
import { ControlCircuits } from '../model/models';
import { Device } from '../model/models';
import { DeviceItem } from '../model/models';
import { DeviceItems } from '../model/models';
import { DevicePluginParam } from '../model/models';
import { DevicePluginParams } from '../model/models';
import { Devices } from '../model/models';
import { DiPluginParam } from '../model/models';
import { DiPluginParams } from '../model/models';
import { DiType } from '../model/models';
import { DiTypes } from '../model/models';
import { Measure } from '../model/models';
import { Measures } from '../model/models';
import { ParamType } from '../model/models';
import { ParamTypes } from '../model/models';
import { Plugin } from '../model/models';
import { Plugins } from '../model/models';
import { Project } from '../model/models';
import { ProjectParam } from '../model/models';
import { ProjectParams } from '../model/models';
import { Projects } from '../model/models';
import { SaveTimer } from '../model/models';
import { SaveTimers } from '../model/models';
import { Section } from '../model/models';
import { SectionParam } from '../model/models';
import { SectionParams } from '../model/models';
import { Sections } from '../model/models';
import { Translation } from '../model/models';
import { Translations } from '../model/models';
import { ValueView } from '../model/models';
import { ValueViews } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ProjectServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete Cc Di
     * 
     * @param ccId Cc identifier
     * @param diId Di identifier
     */
    ccDiDelete(ccId: number, diId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Di
     * 
     * @param ccId Cc identifier
     * @param diId Di identifier
     */
    ccDiGet(ccId: number, diId: number, extraHttpRequestParams?: any): Observable<CcDi>;

    /**
     * List all Cc Dis
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param ccId Cc identifier
     */
    ccDiListGet(limit: number, start: number, ccId: number, extraHttpRequestParams?: any): Observable<CcDis>;

    /**
     * Create a Cc Di
     * 
     * @param ccDi 
     */
    ccDiPost(ccDi: CcDi, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Cc Mode Type
     * 
     * @param id Primary identifier (int)
     */
    ccModeTypeDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Mode Type
     * 
     * @param id Primary identifier (int)
     */
    ccModeTypeGet(id: number, extraHttpRequestParams?: any): Observable<CcModeType>;

    /**
     * List all CC mode types
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param ccTypeId CC Type Id for filtering
     * @param projectId ProjectId for filtering
     */
    ccModeTypeListGet(limit: number, start: number, ccTypeId?: number, projectId?: string, extraHttpRequestParams?: any): Observable<CcModeTypes>;

    /**
     * Update a Cc Mode Type
     * 
     * @param ccModeType 
     */
    ccModeTypePatch(ccModeType: CcModeType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Cc Mode Type
     * 
     * @param ccModeType 
     */
    ccModeTypePost(ccModeType: CcModeType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Cc Param
     * 
     * @param ccId Cc identifier
     * @param paramId Param identifier
     */
    ccParamDelete(ccId: number, paramId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Param
     * 
     * @param ccId Cc identifier
     * @param paramId Param identifier
     */
    ccParamGet(ccId: number, paramId: number, extraHttpRequestParams?: any): Observable<CcParam>;

    /**
     * List all Cc Params
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param ccId Cc identifier
     */
    ccParamListGet(limit: number, start: number, ccId: number, extraHttpRequestParams?: any): Observable<CcParams>;

    /**
     * Create a Cc Param
     * 
     * @param ccParam 
     */
    ccParamPost(ccParam: CcParam, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Cc Status Category
     * 
     * @param id Primary identifier (int)
     */
    ccStatusCategoryDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Status Category
     * 
     * @param id Primary identifier (int)
     */
    ccStatusCategoryGet(id: number, extraHttpRequestParams?: any): Observable<CcStatusCategory>;

    /**
     * List all CC status categories
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    ccStatusCategoryListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<CcStatusCategories>;

    /**
     * Update a Cc Status Category
     * 
     * @param ccStatusCategory 
     */
    ccStatusCategoryPatch(ccStatusCategory: CcStatusCategory, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Cc Status Category
     * 
     * @param ccStatusCategory 
     */
    ccStatusCategoryPost(ccStatusCategory: CcStatusCategory, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Cc Status Type
     * 
     * @param id Primary identifier (int)
     */
    ccStatusTypeDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Status Type
     * 
     * @param id Primary identifier (int)
     */
    ccStatusTypeGet(id: number, extraHttpRequestParams?: any): Observable<CcStatusType>;

    /**
     * List all CC status types
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param ccTypeId CC Type Id
     */
    ccStatusTypeListGet(limit: number, start: number, ccTypeId: number, extraHttpRequestParams?: any): Observable<CcStatusTypes>;

    /**
     * Update a Cc Status Type
     * 
     * @param ccStatusType 
     */
    ccStatusTypePatch(ccStatusType: CcStatusType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Cc Status Type
     * 
     * @param ccStatusType 
     */
    ccStatusTypePost(ccStatusType: CcStatusType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Cc Type
     * 
     * @param id Primary identifier (int)
     */
    ccTypeDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Cc Type Di Type
     * 
     * @param ccTypeId CC Type Id
     * @param diTypeId Di Type Id
     */
    ccTypeDiTypeDelete(ccTypeId: number, diTypeId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Type Di Type
     * 
     * @param ccTypeId CC Type Id
     * @param diTypeId Di Type Id
     */
    ccTypeDiTypeGet(ccTypeId: number, diTypeId: number, extraHttpRequestParams?: any): Observable<CcTypeDiType>;

    /**
     * List all Cc Type Di Types
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param ccTypeId CC Type Id
     */
    ccTypeDiTypeListGet(limit: number, start: number, ccTypeId: number, extraHttpRequestParams?: any): Observable<CcTypeDiTypes>;

    /**
     * Create a Cc Type Di Type
     * 
     * @param ccTypeDiType 
     */
    ccTypeDiTypePost(ccTypeDiType: CcTypeDiType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Type
     * 
     * @param id Primary identifier (int)
     */
    ccTypeGet(id: number, extraHttpRequestParams?: any): Observable<CcType>;

    /**
     * List all CC types
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    ccTypeListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<CcTypes>;

    /**
     * Delete Cc Type Param
     * 
     * @param ccTypeId CC Type Id
     * @param paramId Param identifier
     */
    ccTypeParamDelete(ccTypeId: number, paramId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Cc Type Param
     * 
     * @param ccTypeId CC Type Id
     * @param paramId Param identifier
     */
    ccTypeParamGet(ccTypeId: number, paramId: number, extraHttpRequestParams?: any): Observable<CcTypeParam>;

    /**
     * List all Cc Type Param
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param ccTypeId CC Type Id
     */
    ccTypeParamListGet(limit: number, start: number, ccTypeId: number, extraHttpRequestParams?: any): Observable<CcTypeParams>;

    /**
     * Create a Cc Type Param
     * 
     * @param ccTypeParam 
     */
    ccTypeParamPost(ccTypeParam: CcTypeParam, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a Cc Type
     * 
     * @param ccType 
     */
    ccTypePatch(ccType: CcType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Cc Type
     * 
     * @param ccType 
     */
    ccTypePost(ccType: CcType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Code
     * 
     * @param id Primary identifier (int)
     */
    codeDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Code
     * 
     * @param id Primary identifier (int)
     */
    codeGet(id: number, extraHttpRequestParams?: any): Observable<Code>;

    /**
     * List all codes
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    codeListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<Codes>;

    /**
     * Update a Code
     * 
     * @param code 
     */
    codePatch(code: Code, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Code
     * 
     * @param code 
     */
    codePost(code: Code, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Control Circuit
     * 
     * @param id Primary identifier (int)
     */
    controlCircuitDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Control Circuit
     * 
     * @param id Primary identifier (int)
     */
    controlCircuitGet(id: number, extraHttpRequestParams?: any): Observable<ControlCircuit>;

    /**
     * List all control circuits
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param sectionId sectionId for filtering
     */
    controlCircuitListGet(limit: number, start: number, sectionId: number, extraHttpRequestParams?: any): Observable<ControlCircuits>;

    /**
     * Update a Control Circuit
     * 
     * @param controlCircuit 
     */
    controlCircuitPatch(controlCircuit: ControlCircuit, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Control Circuit
     * 
     * @param controlCircuit 
     */
    controlCircuitPost(controlCircuit: ControlCircuit, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Device
     * 
     * @param id Primary identifier (int)
     */
    deviceDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Device
     * 
     * @param id Primary identifier (int)
     */
    deviceGet(id: number, extraHttpRequestParams?: any): Observable<Device>;

    /**
     * Delete Device Item
     * 
     * @param id Primary identifier (int)
     */
    deviceItemDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Device Item
     * 
     * @param id Primary identifier (int)
     */
    deviceItemGet(id: number, extraHttpRequestParams?: any): Observable<DeviceItem>;

    /**
     * List all device items
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param deviceId Device Id
     */
    deviceItemListGet(limit: number, start: number, deviceId: number, extraHttpRequestParams?: any): Observable<DeviceItems>;

    /**
     * Update a Device Item
     * 
     * @param deviceItem 
     */
    deviceItemPatch(deviceItem: DeviceItem, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Device Item
     * 
     * @param deviceItem 
     */
    deviceItemPost(deviceItem: DeviceItem, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * List all devices
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    deviceListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<Devices>;

    /**
     * Update a Device
     * 
     * @param device 
     */
    devicePatch(device: Device, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Device Plugin Param
     * 
     * @param deviceId Device Id
     * @param paramId Param identifier
     */
    devicePluginParamDelete(deviceId: number, paramId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Device Plugin Param
     * 
     * @param deviceId Device Id
     * @param paramId Param identifier
     */
    devicePluginParamGet(deviceId: number, paramId: number, extraHttpRequestParams?: any): Observable<DevicePluginParam>;

    /**
     * List all Device Plugin Param
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param deviceId Device Id
     */
    devicePluginParamListGet(limit: number, start: number, deviceId: number, extraHttpRequestParams?: any): Observable<DevicePluginParams>;

    /**
     * Create a Device Plugin Param
     * 
     * @param devicePluginParam 
     */
    devicePluginParamPost(devicePluginParam: DevicePluginParam, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Device
     * 
     * @param device 
     */
    devicePost(device: Device, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete DI Plugin Param
     * 
     * @param diTypeId Di Type Id
     * @param paramId Param identifier
     */
    diPluginParamDelete(diTypeId: number, paramId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one DI Plugin Param
     * 
     * @param diTypeId Di Type Id
     * @param paramId Param identifier
     */
    diPluginParamGet(diTypeId: number, paramId: number, extraHttpRequestParams?: any): Observable<DiPluginParam>;

    /**
     * List all DI Plugin Param
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param diTypeId Di Type Id
     */
    diPluginParamListGet(limit: number, start: number, diTypeId: number, extraHttpRequestParams?: any): Observable<DiPluginParams>;

    /**
     * Create a DI Plugin Param
     * 
     * @param diPluginParam 
     */
    diPluginParamPost(diPluginParam: DiPluginParam, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Di Type
     * 
     * @param id Primary identifier (int)
     */
    diTypeDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Di Type
     * 
     * @param id Primary identifier (int)
     */
    diTypeGet(id: number, extraHttpRequestParams?: any): Observable<DiType>;

    /**
     * List all di types
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    diTypeListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<DiTypes>;

    /**
     * Update a Di Type
     * 
     * @param diType 
     */
    diTypePatch(diType: DiType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Di Type
     * 
     * @param diType 
     */
    diTypePost(diType: DiType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Measure
     * 
     * @param id Primary identifier (int)
     */
    measureDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Measure
     * 
     * @param id Primary identifier (int)
     */
    measureGet(id: number, extraHttpRequestParams?: any): Observable<Measure>;

    /**
     * List all measures
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    measureListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<Measures>;

    /**
     * Update a Measure
     * 
     * @param measure 
     */
    measurePatch(measure: Measure, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Measure
     * 
     * @param measure 
     */
    measurePost(measure: Measure, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete param type
     * 
     * @param id Primary identifier (int)
     */
    paramTypeDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one param-type
     * 
     * @param id Primary identifier (int)
     */
    paramTypeGet(id: number, extraHttpRequestParams?: any): Observable<ParamType>;

    /**
     * List all param types
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    paramTypeListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<ParamTypes>;

    /**
     * Update a param type
     * 
     * @param paramType 
     */
    paramTypePatch(paramType: ParamType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a param type
     * 
     * @param paramType 
     */
    paramTypePost(paramType: ParamType, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Plugin
     * 
     * @param id Primary identifier (int)
     */
    pluginDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Plugin
     * 
     * @param id Primary identifier (int)
     */
    pluginGet(id: number, extraHttpRequestParams?: any): Observable<Plugin>;

    /**
     * List all plugins
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    pluginListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<Plugins>;

    /**
     * Update a Plugin
     * 
     * @param plugin 
     */
    pluginPatch(plugin: Plugin, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Plugin
     * 
     * @param plugin 
     */
    pluginPost(plugin: Plugin, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete project
     * 
     * @param id Project identifier
     */
    projectDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one project
     * 
     * @param id Project identifier
     * @param key Project key
     */
    projectGet(id?: string, key?: string, extraHttpRequestParams?: any): Observable<Project>;

    /**
     * List all projects
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     */
    projectListGet(limit: number, start: number, extraHttpRequestParams?: any): Observable<Projects>;

    /**
     * Delete Project Param
     * 
     * @param projectId projectId for filtering
     * @param paramId Param identifier
     */
    projectParamDelete(projectId: string, paramId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Project Param
     * 
     * @param projectId projectId for filtering
     * @param paramId Param identifier
     */
    projectParamGet(projectId: string, paramId: number, extraHttpRequestParams?: any): Observable<ProjectParam>;

    /**
     * List all Project Params
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    projectParamListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<ProjectParams>;

    /**
     * Create a Project Param
     * 
     * @param projectParam 
     */
    projectParamPost(projectParam: ProjectParam, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a project
     * 
     * @param project 
     */
    projectPatch(project: Project, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a project
     * 
     * @param project 
     */
    projectPost(project: Project, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Save Timer
     * 
     * @param id Primary identifier (int)
     */
    saveTimerDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Save Timer
     * 
     * @param id Primary identifier (int)
     */
    saveTimerGet(id: number, extraHttpRequestParams?: any): Observable<SaveTimer>;

    /**
     * List all save timers
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    saveTimerListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<SaveTimers>;

    /**
     * Update a Save Timer
     * 
     * @param saveTimer 
     */
    saveTimerPatch(saveTimer: SaveTimer, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Save Timer
     * 
     * @param saveTimer 
     */
    saveTimerPost(saveTimer: SaveTimer, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete section
     * 
     * @param id Primary identifier (int)
     */
    sectionDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one section
     * 
     * @param id Primary identifier (int)
     */
    sectionGet(id: number, extraHttpRequestParams?: any): Observable<Section>;

    /**
     * List all sections
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    sectionListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<Sections>;

    /**
     * Delete Section Param
     * 
     * @param sectionId sectionId for filtering
     * @param paramId Param identifier
     */
    sectionParamDelete(sectionId: number, paramId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Section Param
     * 
     * @param sectionId sectionId for filtering
     * @param paramId Param identifier
     */
    sectionParamGet(sectionId: number, paramId: number, extraHttpRequestParams?: any): Observable<SectionParam>;

    /**
     * List all Section Params
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param sectionId sectionId for filtering
     */
    sectionParamListGet(limit: number, start: number, sectionId: number, extraHttpRequestParams?: any): Observable<SectionParams>;

    /**
     * Create a Section Param
     * 
     * @param sectionParam 
     */
    sectionParamPost(sectionParam: SectionParam, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a section
     * 
     * @param section 
     */
    sectionPatch(section: Section, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a section
     * 
     * @param section 
     */
    sectionPost(section: Section, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Translation
     * 
     * @param id Primary identifier (int)
     */
    translationDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Translation
     * 
     * @param id Primary identifier (int)
     */
    translationGet(id: number, extraHttpRequestParams?: any): Observable<Translation>;

    /**
     * List all translations
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param projectId projectId for filtering
     */
    translationListGet(limit: number, start: number, projectId: string, extraHttpRequestParams?: any): Observable<Translations>;

    /**
     * Update a Translation
     * 
     * @param translation 
     */
    translationPatch(translation: Translation, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Translation
     * 
     * @param translation 
     */
    translationPost(translation: Translation, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete Value View
     * 
     * @param id Primary identifier (int)
     */
    valueViewDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one Value View
     * 
     * @param id Primary identifier (int)
     */
    valueViewGet(id: number, extraHttpRequestParams?: any): Observable<ValueView>;

    /**
     * List all value views
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param diTypeId Di Type Id
     */
    valueViewListGet(limit: number, start: number, diTypeId: number, extraHttpRequestParams?: any): Observable<ValueViews>;

    /**
     * Update a Value View
     * 
     * @param valueView 
     */
    valueViewPatch(valueView: ValueView, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create a Value View
     * 
     * @param valueView 
     */
    valueViewPost(valueView: ValueView, extraHttpRequestParams?: any): Observable<{}>;

}
