/**
 * Svetit MS Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Group } from '../model/models';
import { Groups } from '../model/models';
import { Invitation } from '../model/models';
import { InvitationRole } from '../model/models';
import { Invitations } from '../model/models';
import { Link } from '../model/models';
import { Links } from '../model/models';
import { Space } from '../model/models';
import { SpaceParams } from '../model/models';
import { Spaces } from '../model/models';
import { User } from '../model/models';
import { Users } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SpaceServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete group
     * 
     * @param id Primary identifier (int)
     * @param spaceKey Space\&#39;s key for proxying
     */
    groupDelete(id: number, spaceKey?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get one space group
     * 
     * @param id Primary identifier (int)
     * @param spaceKey Space\&#39;s key for proxying
     */
    groupGet(id: number, spaceKey?: string, extraHttpRequestParams?: any): Observable<Group>;

    /**
     * List all groups
     * 
     * @param limit How many items to return at one time (max 1000)
     * @param start Offset position
     * @param spaceKey Space\&#39;s key for proxying
     */
    groupListGet(limit: number, start: number, spaceKey?: string, extraHttpRequestParams?: any): Observable<Groups>;

    /**
     * Create a group
     * 
     * @param group 
     * @param spaceKey Space\&#39;s key for proxying
     */
    groupPost(group: Group, spaceKey?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a group
     * 
     * @param group 
     * @param spaceKey Space\&#39;s key for proxying
     */
    groupPut(group: Group, spaceKey?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get space parameters info
     * 
     */
    infoGet(extraHttpRequestParams?: any): Observable<SpaceParams>;

    /**
     * Introspect token
     * 
     * @param xOriginalURI URI with space key for introspection
     * @param xApiPrefix Api prefix
     * @param space cookie with space token
     */
    introspectGet(xOriginalURI: string, xApiPrefix: string, space?: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete invitation
     * 
     * @param id Invitation id
     */
    invitationDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get invitations list
     * 
     * @param start Offset position
     * @param limit How many items to return at one time (max 1000)
     * @param spaceId Space Id
     */
    invitationGet(start: number, limit: number, spaceId?: string, extraHttpRequestParams?: any): Observable<Invitations>;

    /**
     * Join space by invitation
     * 
     * @param id Invitation id
     */
    invitationPatch(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create invitation
     * 
     * @param invitation 
     */
    invitationPost(invitation?: Invitation, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Change role in invitation
     * 
     * @param id Invitation id
     * @param invitationRole 
     */
    invitationPut(id: number, invitationRole: InvitationRole, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Delete link
     * 
     * @param id Link id
     */
    linkDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get links list
     * 
     * @param start Offset position
     * @param limit How many items to return at one time (max 1000)
     * @param spaceId Space Id
     */
    linkGet(start: number, limit: number, spaceId?: string, extraHttpRequestParams?: any): Observable<Links>;

    /**
     * Create invitation by link
     * 
     * @param id Link id
     */
    linkPost(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create link
     * 
     * @param link 
     */
    linkPut(link: Link, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get spaces available to join
     * 
     * @param start Offset position
     * @param limit How many items to return at one time (max 1000)
     * @param spaceName Space Name
     */
    listAvailableGet(start: number, limit: number, spaceName?: string, extraHttpRequestParams?: any): Observable<Spaces>;

    /**
     * Get spaces list
     * 
     * @param start Offset position
     * @param limit How many items to return at one time (max 1000)
     */
    listGet(start: number, limit: number, extraHttpRequestParams?: any): Observable<Spaces>;

    /**
     * Delete space
     * 
     * @param id Id UUID
     */
    spaceDelete(id: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get space
     * 
     * @param id Space Id
     * @param key Space Key
     * @param link Link
     */
    spaceGet(id?: string, key?: string, link?: string, extraHttpRequestParams?: any): Observable<Space>;

    /**
     * Check space existence
     * 
     * @param key Space Key
     */
    spaceHead(key: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Create space
     * 
     * @param space 
     */
    spacePost(space: Space, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get space users list
     * 
     * @param spaceId Space Id
     * @param start Offset position
     * @param limit How many items to return at one time (max 1000)
     */
    spaceUserListGet(spaceId: string, start: number, limit: number, extraHttpRequestParams?: any): Observable<Users>;

    /**
     * Delete space user
     * 
     * @param userId Space User Id
     * @param spaceId Space Id
     */
    userManageDelete(userId: string, spaceId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update space user
     * 
     * @param user 
     */
    userManagePatch(user: User, extraHttpRequestParams?: any): Observable<{}>;

}
