CREATE SCHEMA IF NOT EXISTS auth;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE auth.session (
	id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	token TEXT NOT NULL,
	createdAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
	expiredAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
	userId VARCHAR(36) NOT NULL,
	device TEXT NOT NULL,
	accessToken TEXT NOT NULL,
	refreshToken TEXT NOT NULL,
	idToken TEXT NOT NULL,
	active BOOLEAN NOT NULL
);

CREATE TABLE auth.state (
	id SERIAL PRIMARY KEY,
	state TEXT NOT NULL,
	redirectUrl TEXT NOT NULL,
	createdAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);
