CREATE SCHEMA IF NOT EXISTS space;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE space.space (
	id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	name TEXT NOT NULL,
	key VARCHAR(32) NOT NULL,
	requestsAllowed BOOLEAN NOT NULL,
	createdAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE UNIQUE INDEX idx_space_key ON space.space (key);

CREATE TABLE space.invitation (
	id SERIAL PRIMARY KEY,
	spaceId UUID NOT NULL REFERENCES space.space (id),
	creatorId TEXT NOT NULL,
	userId TEXT NOT NULL,
	role SMALLINT,
	createdAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT
);

CREATE TABLE space.link (
	id UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
	spaceId UUID NOT NULL REFERENCES space.space (id),
	creatorId TEXT NOT NULL,
	name TEXT NOT NULL,
	createdAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
	expiredAt BIGINT NOT NULL
);

CREATE TABLE space.user (
	spaceId UUID NOT NULL REFERENCES space.space (id),
	userId TEXT NOT NULL,
	isOwner BOOLEAN NOT NULL,
	joinedAt BIGINT NOT NULL DEFAULT EXTRACT(EPOCH FROM CURRENT_TIMESTAMP)::BIGINT,
	role SMALLINT NOT NULL,

	PRIMARY KEY (spaceId, userId)
);
