components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        monitor-task-processor:            # Make a separate task processor for monitoring tasks.
            worker_threads: $worker-monitor-threads
            thread_name: monitor-worker

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
            listener-monitor:
                port: $server-metrics-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: monitor-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        database:
          dbconnection: $db-url
          blocking_task_processor: fs-task-processor
          dns_resolver: async
          sync-start: true

        tests-control:
            load-enabled: $is_testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        repository: {}

        main-service:
            items-limit-for-list: $items-limit-for-list
            json-schemas-path: $json-schemas-path

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-node:
          path: /node
          method: GET,POST,PUT,DELETE
          task_processor: main-task-processor

        handler-node-list:
          path: /node/list
          method: GET
          task_processor: main-task-processor

        handler-node-project:
          path: /node/project
          method: GET,POST,DELETE
          task_processor: main-task-processor

        handler-node-project-list:
          path: /node/project/list
          method: GET
          task_processor: main-task-processor
        handler-server-monitor:
            path: /statistics
            method: GET
            task_processor: monitor-task-processor
            common-labels:
                application: sample application
                zone: some
            format: json
