/**
 * Svetit MS Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Invitation { 
    id?: number;
    spaceId: string;
    creatorId?: string;
    userId: string;
    role: Invitation.RoleEnum;
    createdAt?: number;
}
export namespace Invitation {
    export type RoleEnum = 'guest' | 'user' | 'admin';
    export const RoleEnum = {
        Guest: 'guest' as RoleEnum,
        User: 'user' as RoleEnum,
        Admin: 'admin' as RoleEnum
    };
}


