/**
 * Svetit MS Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParamType { 
    id?: number;
    projectId?: string;
    parentId: string | null;
    key: string;
    name: string;
    description: string;
    valueType: ParamType.ValueTypeEnum;
}
export namespace ParamType {
    export type ValueTypeEnum = 'int' | 'bool' | 'float' | 'string' | 'bytes' | 'time' | 'range' | 'combo';
    export const ValueTypeEnum = {
        Int: 'int' as ValueTypeEnum,
        Bool: 'bool' as ValueTypeEnum,
        Float: 'float' as ValueTypeEnum,
        String: 'string' as ValueTypeEnum,
        Bytes: 'bytes' as ValueTypeEnum,
        Time: 'time' as ValueTypeEnum,
        Range: 'range' as ValueTypeEnum,
        Combo: 'combo' as ValueTypeEnum
    };
}


