/**
 * Svetit MS Project
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Project { 
    id?: string;
    spaceId: string;
    key: string;
    name: string;
    description?: string;
    changedAt?: string;
    sync: Project.SyncEnum;
}
export namespace Project {
    export type SyncEnum = 'projectToNode' | 'nodeToProject';
    export const SyncEnum = {
        ProjectToNode: 'projectToNode' as SyncEnum,
        NodeToProject: 'nodeToProject' as SyncEnum
    };
}


