components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        database:
          dbconnection: $db-url
          blocking_task_processor: fs-task-processor
          dns_resolver: async
          sync-start: true

        tests-control:
            load-enabled: $is_testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        repository: {}
        main-service:
            items-limit-for-list: $items-limit-for-list

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-details:
          path: /project/details
          method: POST
          task_processor: main-task-processor

        handler-project:
          path: /project
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-project-list:
          path: /project/list
          method: GET
          task_processor: main-task-processor

        handler-param-type:
          path: /project/param-type
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-param-type-list:
          path: /project/param-type/list
          method: GET
          task_processor: main-task-processor

        handler-project-param:
          path: /project/project-param
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-project-param-list:
          path: /project/project-param/list
          method: GET
          task_processor: main-task-processor

        handler-section:
          path: /project/section
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-section-list:
          path: /project/section/list
          method: GET
          task_processor: main-task-processor

        handler-section-param:
          path: /project/section-param
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-section-param-list:
          path: /project/section-param/list
          method: GET
          task_processor: main-task-processor

        handler-cc-type:
          path: /project/cc-type
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-type-list:
          path: /project/cc-type/list
          method: GET
          task_processor: main-task-processor

        handler-control-circuit:
          path: /project/control-circuit
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-control-circuit-list:
          path: /project/control-circuit/list
          method: GET
          task_processor: main-task-processor

        handler-plugin:
          path: /project/plugin
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-plugin-list:
          path: /project/plugin/list
          method: GET
          task_processor: main-task-processor

        handler-device:
          path: /project/device
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-device-list:
          path: /project/device/list
          method: GET
          task_processor: main-task-processor

        handler-device-plugin-param:
          path: /project/device-plugin-param
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-device-plugin-param-list:
          path: /project/device-plugin-param/list
          method: GET
          task_processor: main-task-processor

        handler-code:
          path: /project/code
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-code-list:
          path: /project/code/list
          method: GET
          task_processor: main-task-processor

        handler-measure:
          path: /project/measure
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-measure-list:
          path: /project/measure/list
          method: GET
          task_processor: main-task-processor

        handler-save-timer:
          path: /project/save-timer
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-save-timer-list:
          path: /project/save-timer/list
          method: GET
          task_processor: main-task-processor

        handler-cc-type-param:
          path: /project/cc-type-param
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-type-param-list:
          path: /project/cc-type-param/list
          method: GET
          task_processor: main-task-processor

        handler-di-type:
          path: /project/di-type
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-di-type-list:
          path: /project/di-type/list
          method: GET
          task_processor: main-task-processor

        handler-di-plugin-param:
          path: /project/di-plugin-param
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-di-plugin-param-list:
          path: /project/di-plugin-param/list
          method: GET
          task_processor: main-task-processor

        handler-cc-type-di-type:
          path: /project/cc-type-di-type
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-type-di-type-list:
          path: /project/cc-type-di-type/list
          method: GET
          task_processor: main-task-processor

        handler-device-item:
          path: /project/device-item
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-device-item-list:
          path: /project/device-item/list
          method: GET
          task_processor: main-task-processor

        handler-cc-mode-type:
          path: /project/cc-mode-type
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-mode-type-list:
          path: /project/cc-mode-type/list
          method: GET
          task_processor: main-task-processor

        handler-cc-di:
          path: /project/cc-di
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-di-list:
          path: /project/cc-di/list
          method: GET
          task_processor: main-task-processor

        handler-cc-param:
          path: /project/cc-param
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-param-list:
          path: /project/cc-param/list
          method: GET
          task_processor: main-task-processor

        handler-cc-status-category:
          path: /project/cc-status-category
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-status-category-list:
          path: /project/cc-status-category/list
          method: GET
          task_processor: main-task-processor

        handler-cc-status-type:
          path: /project/cc-status-type
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-cc-status-type-list:
          path: /project/cc-status-type/list
          method: GET
          task_processor: main-task-processor

        handler-value-view:
          path: /project/value-view
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-value-view-list:
          path: /project/value-view/list
          method: GET
          task_processor: main-task-processor

        handler-translation:
          path: /project/translation
          method: GET,POST,PATCH,DELETE
          task_processor: main-task-processor

        handler-translation-list:
          path: /project/translation/list
          method: GET
          task_processor: main-task-processor
