# global config
global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
- job_name: 'svetit_node'
  metrics_path: /metrics
  static_configs:
    - targets: ['node:7777']
  params:
    format: ['prometheus-untyped']
